package br.com.olatcg_backend.domain.homology.search;

import br.com.olatcg_backend.domain.pairwise.alignment.PairwiseAlignment;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

@AllArgsConstructor
@Getter
@Setter
public class HomologyHit {

    public static String DEFAULT_DESCRIPTION = "Generated by OLATCG homology analysis";

    private PairwiseAlignment pairwiseAlignment;
    private String taxonomy;
}
